name: Build a Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set FOXGLOVE_VERSION env
      run: echo "FOXGLOVE_VERSION=$(yq .version package.json | tr -d '\"')" >> $GITHUB_ENV
      shell: bash

    - name: Set SHORT_DATE env
      run: echo "SHORT_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push (production)
      if: github.ref_name == 'main'
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64, linux/arm64
        push: true
        file: ./husarion_add_ons/Dockerfile
        build-args: |
          FOXGLOVE_VERSION=${{ env.FOXGLOVE_VERSION }}
        tags: |
          husarion/foxglove:${{ env.FOXGLOVE_VERSION }}-${{ env.SHORT_DATE }}
          husarion/foxglove:${{ env.FOXGLOVE_VERSION }}
          husarion/foxglove:nightly
        # cache-from: type=registry,ref=husarnet/dds-router
        cache-to: type=inline

    - name: Build and push (feature branch)
      if: github.ref_name != 'main'
      uses: docker/build-push-action@v3
      with:
        # platforms: linux/amd64, linux/arm64
        platforms: linux/amd64
        push: true
        file: ./husarion_add_ons/Dockerfile
        build-args: |
          FOXGLOVE_VERSION=${{ env.FOXGLOVE_VERSION }}
        tags: |
          husarion/foxglove:${{ github.head_ref || github.ref_name }}-${{ env.FOXGLOVE_VERSION }}
          husarion/foxglove:nightly
        # cache-from: type=registry,ref=husarnet/dds-router-${{ github.head_ref || github.ref_name }}
        cache-to: type=inline
